etcd_port : 2379
log_level : "debug"
app_port : 3000
grpcEnabled : true
kube:
  config: out-of-cluster
  context: minikube
  job:
    active.deadline.seconds: 60
    retries: 0
  service.account.name: default
  wait.for.resource.poll.count: 5
  log.process.wait.time: 60
log.level: debug
app.port: 5000
default.namespace: default
job.pod.annotations: "{\"key.one\":\"true\"}"