// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: procProto/process.proto

package procProto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Proc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *Proc) Reset() {
	*x = Proc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_procProto_process_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proc) ProtoMessage() {}

func (x *Proc) ProtoReflect() protoreflect.Message {
	mi := &file_procProto_process_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proc.ProtoReflect.Descriptor instead.
func (*Proc) Descriptor() ([]byte, []int) {
	return file_procProto_process_proto_rawDescGZIP(), []int{0}
}

func (x *Proc) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Proc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Proc) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type ProcID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value   string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ProcID) Reset() {
	*x = ProcID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_procProto_process_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcID) ProtoMessage() {}

func (x *ProcID) ProtoReflect() protoreflect.Message {
	mi := &file_procProto_process_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcID.ProtoReflect.Descriptor instead.
func (*ProcID) Descriptor() ([]byte, []int) {
	return file_procProto_process_proto_rawDescGZIP(), []int{1}
}

func (x *ProcID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ProcID) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RequestForCreateProc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *RequestForCreateProc) Reset() {
	*x = RequestForCreateProc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_procProto_process_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForCreateProc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForCreateProc) ProtoMessage() {}

func (x *RequestForCreateProc) ProtoReflect() protoreflect.Message {
	mi := &file_procProto_process_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForCreateProc.ProtoReflect.Descriptor instead.
func (*RequestForCreateProc) Descriptor() ([]byte, []int) {
	return file_procProto_process_proto_rawDescGZIP(), []int{2}
}

func (x *RequestForCreateProc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestForCreateProc) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type RequestForReadByID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *RequestForReadByID) Reset() {
	*x = RequestForReadByID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_procProto_process_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForReadByID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForReadByID) ProtoMessage() {}

func (x *RequestForReadByID) ProtoReflect() protoreflect.Message {
	mi := &file_procProto_process_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForReadByID.ProtoReflect.Descriptor instead.
func (*RequestForReadByID) Descriptor() ([]byte, []int) {
	return file_procProto_process_proto_rawDescGZIP(), []int{3}
}

func (x *RequestForReadByID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type RequestForUpdateProcByID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author string `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *RequestForUpdateProcByID) Reset() {
	*x = RequestForUpdateProcByID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_procProto_process_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForUpdateProcByID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForUpdateProcByID) ProtoMessage() {}

func (x *RequestForUpdateProcByID) ProtoReflect() protoreflect.Message {
	mi := &file_procProto_process_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForUpdateProcByID.ProtoReflect.Descriptor instead.
func (*RequestForUpdateProcByID) Descriptor() ([]byte, []int) {
	return file_procProto_process_proto_rawDescGZIP(), []int{4}
}

func (x *RequestForUpdateProcByID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *RequestForUpdateProcByID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RequestForUpdateProcByID) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type RequestForDeleteByID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *RequestForDeleteByID) Reset() {
	*x = RequestForDeleteByID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_procProto_process_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestForDeleteByID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestForDeleteByID) ProtoMessage() {}

func (x *RequestForDeleteByID) ProtoReflect() protoreflect.Message {
	mi := &file_procProto_process_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestForDeleteByID.ProtoReflect.Descriptor instead.
func (*RequestForDeleteByID) Descriptor() ([]byte, []int) {
	return file_procProto_process_proto_rawDescGZIP(), []int{5}
}

func (x *RequestForDeleteByID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

var File_procProto_process_proto protoreflect.FileDescriptor

var file_procProto_process_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x04, 0x50, 0x72, 0x6f,
	0x63, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x38, 0x0a,
	0x06, 0x50, 0x72, 0x6f, 0x63, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x42, 0x0a, 0x14, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x24, 0x0a, 0x12, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x64, 0x42, 0x79, 0x49,
	0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x22, 0x56, 0x0a, 0x18, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x42, 0x79, 0x49, 0x44, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x26, 0x0a, 0x14, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x49,
	0x44, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x32, 0xcf, 0x01, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2c, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x12,
	0x15, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x1a, 0x07, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x49, 0x44, 0x12,
	0x2a, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x42, 0x79, 0x49, 0x44, 0x12,
	0x13, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x61, 0x64,
	0x42, 0x79, 0x49, 0x44, 0x1a, 0x05, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x12, 0x34, 0x0a, 0x0e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x42, 0x79, 0x49, 0x44, 0x12, 0x19, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x63, 0x42, 0x79, 0x49, 0x44, 0x1a, 0x07, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x49,
	0x44, 0x12, 0x30, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x63, 0x42,
	0x79, 0x49, 0x44, 0x12, 0x15, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x6f, 0x72,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x49, 0x44, 0x1a, 0x07, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x49, 0x44, 0x42, 0x14, 0x5a, 0x12, 0x63, 0x72, 0x75, 0x64, 0x2d, 0x74, 0x6f, 0x79, 0x2f,
	0x70, 0x72, 0x6f, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_procProto_process_proto_rawDescOnce sync.Once
	file_procProto_process_proto_rawDescData = file_procProto_process_proto_rawDesc
)

func file_procProto_process_proto_rawDescGZIP() []byte {
	file_procProto_process_proto_rawDescOnce.Do(func() {
		file_procProto_process_proto_rawDescData = protoimpl.X.CompressGZIP(file_procProto_process_proto_rawDescData)
	})
	return file_procProto_process_proto_rawDescData
}

var file_procProto_process_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_procProto_process_proto_goTypes = []interface{}{
	(*Proc)(nil),                     // 0: Proc
	(*ProcID)(nil),                   // 1: ProcID
	(*RequestForCreateProc)(nil),     // 2: RequestForCreateProc
	(*RequestForReadByID)(nil),       // 3: RequestForReadByID
	(*RequestForUpdateProcByID)(nil), // 4: RequestForUpdateProcByID
	(*RequestForDeleteByID)(nil),     // 5: RequestForDeleteByID
}
var file_procProto_process_proto_depIdxs = []int32{
	2, // 0: ProcService.CreateProc:input_type -> RequestForCreateProc
	3, // 1: ProcService.ReadProcByID:input_type -> RequestForReadByID
	4, // 2: ProcService.UpdateProcByID:input_type -> RequestForUpdateProcByID
	5, // 3: ProcService.DeleteProcByID:input_type -> RequestForDeleteByID
	1, // 4: ProcService.CreateProc:output_type -> ProcID
	0, // 5: ProcService.ReadProcByID:output_type -> Proc
	1, // 6: ProcService.UpdateProcByID:output_type -> ProcID
	1, // 7: ProcService.DeleteProcByID:output_type -> ProcID
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_procProto_process_proto_init() }
func file_procProto_process_proto_init() {
	if File_procProto_process_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_procProto_process_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_procProto_process_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_procProto_process_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestForCreateProc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_procProto_process_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestForReadByID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_procProto_process_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestForUpdateProcByID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_procProto_process_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestForDeleteByID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_procProto_process_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_procProto_process_proto_goTypes,
		DependencyIndexes: file_procProto_process_proto_depIdxs,
		MessageInfos:      file_procProto_process_proto_msgTypes,
	}.Build()
	File_procProto_process_proto = out.File
	file_procProto_process_proto_rawDesc = nil
	file_procProto_process_proto_goTypes = nil
	file_procProto_process_proto_depIdxs = nil
}
